[[redirects]]
  from = "/graphql"
  to = "https://fullstack-test-starter-production.up.railway.app/graphql"
  status = 200
  force = true

[[redirects]]
  from = "/graphql/"
  to = "https://fullstack-test-starter-production.up.railway.app/graphql"
  status = 200
  force = true

[[redirects]]
  from = "/graphql/*"
  to = "https://fullstack-test-starter-production.up.railway.app/graphql"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
